Django8/src/Django8/urls.py
from django.contrib import admin
from django.urls import path, include

from vote.views import *  #vote/view.py 에 있는 모든 함수/클래스 추가 
from vote.views import deleteC

urlpatterns = [
   
    path('admin/', admin.site.urls), #127.0.0.1:8000/admin/
    path('', index, name = 'index' ),#127.0.0.1:8000/
    #URL 등록 시 파이썬 코드에서 URL을 외워서 사용하지 않고,
    #별칭을 이용해서 사용할 수 있도록 name 매개변수에 문자열을 대입
    path('detail/<int:question_id>/',detail,name = 'detail' ),
    #path('admin/',index),
    #URL 추가 http://127.0.0.1:8000주소로 접근시 vore 어플리케이션의
    #view인 index 함수를 호출 하도록 등록
    path('result/<int:question_id>/',result,name='result'),
    path('vote/',vote,name='vote'),
    path('registerQuestion/', registerQ, name='registerQ') ,
    path('registerChoice/', registerC, name='registerC'),
    path('delete/<int:question_id>/',deleteQ,name='deleteQ'),
    path('deleteC/<int:choice_id>/',deleteC,name='deleteC'),
    path('updateQ/<int:question_id>/',updateQ,name="updateQ"),
    path('updateC/<int:choice_id>/',updateC,name="updateC"),
    #127.0.0.1/login/ URL 주소로 요청이 되면 view함수 호출 처리는 
    #customlogin 폴더에 있는 urls.py에서 처리하겠다 라고 등록
    path('login/',include('customlogin.urls')),
    path('auth/',include('social_django.urls',namespace ='social' ) ),
    path('blog/',include('blog.urls') )
]
#파일 관리 모듈 : numpy
from django.conf import settings
from django.conf.urls.static import static
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  




Django8/src/blog/urls.py

from django.urls import path
from .views import *
from blog.view import searchP

app_name = 'blog'

urlpatterns=[
    path('',index.as_view(),name='index'),
    path('<int:post_id>/',detail, name='detail'),
    path('search/',searchP,name='searchP')
    ]

Django8/src/vote/models.py
from django.db import models
from django.contrib.auth.models import User
# 모델클래스 정의시 models.py에 있는 Modle 클래스를 상속받음
class Question(models.Model):
    #저장할 속성을 models.클래스명()으로 객체 생성후 변수에 대입
    #models.CharField : 글자수 제한을 두는 문자열을 저장할 때 사용 
    #models.CharField(max_length=20)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question_text = models.CharField('질문 문구',max_length=200)
    #models.DateTimeField() : 날자 + 시간 정보를 저장할 때 사용
    pub_data = models.DateTimeField('작성일')
    #각 속성에 null변수와 blank 변수를 True 설정하면 값이 비어있어도 
    #객체가 생성되도록 설정
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=100)
    #models.IntegerField() : 정수값을 저장할 때 사용 
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)    
    #models.ForeignKey : 다른 모델클래스와 연결고리를 만들 때 사용 
    #이 때 1:n 관계를 가짐
    #on_delete : 연결지은 모델클래스의 객체가 삭제될 경우 자신도 삭제될것인지 
    #            명시하는 매개변수
    def __str__(self):
        return self.choice_text    

Django8/src/vote/forms.py
'''
Created on 2018. 8. 25.

@author: KGITBANK403-21
'''
#form : HTML코드에서 사용할 입력양식(<form>)을 모델클래스에 맞게
#자동으로 만들어주는 기능 or 커스텀 입력양식을 만드는 기능을 제공함

#class 폼클래스명(ModelForm) : 모델클래스에 관한 폼을 정의
#class 폼클래스명(Form) : HTML에서 사용할 커스텀 폼을 정의
from django.forms.models import ModelForm
#from . import models #현재 폴더(.)에서 models 파일을 임포트 
from .models import * #현재 폴더에 있는 models 파일에서 전체(*)를 임포트

#question_text 값을 입력받을 수 있는 입력양식
class QuestionForm(ModelForm):
    class Meta: #Meta 클래스 정의를 통해 모델 클래스에 관한 정보를 입력
        #model : 모델클래스 명(해당 폼에 매칭할 모델클래스를 작성)
        #fields or exclude 중 하나를 선택해 사용
        #fields : 해당 모델폼을 통해 클라이언트가 입력할수있는 데이터를 명시 
        #         모델클래스의 변수명을 리스트형태로 입력
        #exclude : 모델클래스의 변수 중 명시한 변수명을 제외한 나머지 변수들을 
        #         클라시언트가 작성할 수 있도록 제공
        model = Question #해당클래스가 Qestion 모델클래스와 연동됨을 명시
        #사용자가 question_text 변수에 들어갈 값만 입력할 수 있도록 <input>태그
        #가 생성됨
        #fields = ['question_text']
        #사용자가 pub_date 변수 외에 변수들을 입력할 수 있도록<input>태그가 생성됨
        exclude = ['pub_data','author']
        
        
#선택지 문구, 어떤질문의 선택지인지 선택 할수 있는 입력양식
#Choice 모델클래스를 참고
class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['question','choice_text']
        #exclud=['votes']    
        

Django8/src/vote/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question , Choice 

from django.contrib.auth.decorators import login_required


from django.http.response import HttpResponseRedirect
from django.urls import reverse
#HttpRestponsRedirect : 클라이언트에게 HTML파일을 전달하는것이 아닌 
#URL 주소를 전달 -> 웹 클라이언트는 받은 URL주소로 웹서버에 재요청 
#reverse 함수 : URL의 별칭 (name)을 이용해 URL 주소를 찾는 함수
#(Template 엔진의 url함수와 동일 기능 제공) 
#함수 or 클래스 형태로 뷰 구현
#함수형태로 구현시 첫번째 매개변수로 request를 받아야함
#request : 웹 클라이언트의 요청에 대한 정보를 알고있는 매개변수
'''
def index(request):
    #render(request, html 파일경로, 템플릿에서 사용할 데이터 - 사전형)
    return render(request, 'vote/index.html',{'hello': 'django개발'})
'''
#질문 목록 보기
def index(request):
    #Question.objects.all(): 데이터베이스에 저장된 모든 Question 객체를
    #                        리스트형태로 가져옴 
    list = Question.objects.all()
    print(list)
    
    return render(request, 'vote/index.html',{'question_list':list})



def detail(reqeust,question_id):
    
    #매개변수에 작성한 조건에 따라 모델클래스의 객체 1개를 추출 
    #매개변수이름은 모델클래스에 작성한 변수를 사용가능
    #내부적으로 id변수(고유 키)가 추가됨
    obj = Question.objects.get(id=question_id)
    return render(reqeust, 'vote/detail.html',{'question':obj})
#투표 처리
def vote(request):
    #request.method : 클라이언트의 요청이 GET방식인지 POST방식이 저장한 변수
    #문자열 비교시 "GET"/"POST" 문자열과 같은지 비교 (전부 대문자로 작성)
    if request.method == "POST":#클라이언트 요청이 POST인가?
        #request.POST : POST 요청으로 온 데이터들
        #request.POST.get(name 값) : POST방식으로 들어온 데이터 중
        #name과 같은 데이터를 추출
        #get함수가 반환하는 값은 전부 문자열 
        id = request.POST.get('choice')
        #pk : Choice객체의 id변수와 동일
        obj = get_object_or_404(Choice,pk=id)
        obj.votes += 1 # obj.vote = obj.vote + 1
        obj.save() #객체의 변경 사항을 데이터 베이스에 저장
        #obj.question : Choice 객체가 연결된 Question
        #obj.question.qestion_text : Choice 객체가 연결된 Question 객체에
        #저장된 question_text 변수를 읽기
        return HttpResponseRedirect( reverse('result', 
                                              args=(obj.question.id,)   ) )
    
def result(request, question_id):
    #obj 변수 : Question 객체
    obj = get_object_or_404(Question, pk = question_id)
    return render(request, 'vote/result.html', {'obj':obj})
from .forms import *
import datetime #시간에 관한 모듈
@login_required
def registerQ(request): 
    #하나의 뷰 함수가 사용자
    if request.method == "GET" :
        form = QuestionForm() 
        #QuestionForm 객체 생성. 사용자로부터 입력받을 변수값을 HTML
        #문서에서 처리할수있도록 HTML코드로 변환 가능 
        #객체를 생성한 경우, <input>태그에 값이 비어있는 상태로 사용자에게 전달
        return render(request,'vote/registerQ.html',{'form':form})
    elif request.method == "POST" : 
        #폼 객체 생성시 사용자가 입력한 데이터를 각 폼변수에 대입
        form = QuestionForm(request.POST)
        
        if form.is_valid(): #해당폼에 입력값들이 에러가 없는지 확인
            #form.save() 
            # 해당 폼에 입력값들로 모델클래스 객체를 생성 후 데이터 베이스에 저장 
            obj = form.save(commit=False)#해당 폼에 입력값들로 모델클래스 객체를 생성
            obj.pub_data = datetime.datetime.now()#현재시간을 대입
            obj.author =request.user #글쓴이 등록 
            obj.save()# Question 객체를 데이터베이스에 저장
            return HttpResponseRedirect( reverse( 'detail', args=(obj.id,) ) )
@login_required       
def registerC(request):
    if request.method =="GET":#vote/registerC.html을 사용 
        form = ChoiceForm()
        #request.GET
        print(form.as_table)
        return render(request,'vote/registerC.html', {'form':form})
        #GET방식 처리 코드 만들기 1)폼객체 생성 2)render함수 반환
    
    elif request.method == "POST":
        #1)사용자데이터를 기반으로 폼객체생성 
        form = ChoiceForm(request.POST)
        #2)유효한 값이 들어있는 폼인지 확인 
        if form.is_valid():
            #print(request.user)
            #print(form.cleaned_data['question'].author)
            #print(request.post.get('question'))
            #현재 로그인된 유저와 question 모델클래스 객체에 저장된
            #글쓴이를 비교
            if request.user == form.cleaned_data['question'].author:
                
            #3)모델클래스 객체를 생성 및 데이터베이스에 저장
                obj = form.save()
                return HttpResponseRedirect( 
                reverse('detail',args=(obj.question.id,) ) )
        #4)'detail' 별칭을 가진 URL 반환
        else:
            return render(request, 'vote/registerC.html',{'form':form,
                                'error':'현재 로그인된 유저의 글이 아닙니다.'})
@login_required        
def deleteQ(request,question_id):
    #삭제할 객체 찾기
    #pk=id 동일
    obj = get_object_or_404(Question,pk=question_id)       
    obj.delete() #해당 객체를 데이터베이스에서 제거
    return HttpResponseRedirect(reverse('index',) )
@login_required
def deleteC(request,choice_id):
    obj = get_object_or_404(Choice,pk=choice_id)
    question_id = obj.question.id
    obj.delete()
    return HttpResponseRedirect(reverse('detail', args=(question_id,)))

@login_required
def updateQ(request, question_id):
    obj = get_object_or_404(Question,pk = question_id)
    if request.method == "GET":
        #Question 객체에 저장된 값을 QuestionForm 객체를 생성할 때 입력
        #모델폼의 생성자에 instance 매개변수는 이미 생성된 모델클래스의 객체를
        #넣어야함
        form = QuestionForm(instance = obj)
        return render(request, 'vote/updateQ.html',{"form":form})
    elif request.method == "POST":
        #이미 생성된 Question 객체에 변수값들을 클라이언트가 작성한 내용으로 
        #덮어씌움 
        form = QuestionForm(request.POST, instance = obj)
        if form.is_valid():
            question = form.save()
            #question = form.save(commit=False)
            #question.pub_data = obj.pub_data
            #question.save()
            
            return HttpResponseRedirect(
                reverse('detail',args=(question.id,)))
            
#updateC 제작
#1)view 제작 
@login_required
def updateC(request,choice_id):
        #1-1)Choice 객체 찾기
    obj = get_object_or_404(Choice,pk=choice_id)
    #1-2)GET/POST 구분
    if request.method == "GET":
        #1-3-1-1)GET-폼객체 생성 후 Html 반환
        form = ChoiceForm(instance = obj)
        return render(request,'vote/updateC.html',{'data':form})
    elif request.method =="POST":
        #1-3-2-1)POST- 사용자 입력 + Choice 객체를 통해 생성자 호출
        form = ChoiceForm(request.POST,instance = obj)
        #1-3-2-2)데이터가 유효한지 확인
        if form.is_valid():
            #1-3-2-3)폼객체 저장    
            cho=form.save()
            #cho.question.id
            #1-3-2-4)detail 뷰의 URL 전송
            return HttpResponseRedirect(
                 reverse('detail',args=(cho.question.id,) ) )
        else:#사용자의 입력이 유효하지 않는 데이터인경우
            #다시 html문서를 전달하면서 특정변수에 에러문구 대입
            return render(request, 'vote/updateC.html',
                          {'data':form , 'error':'유효하지않는 입력'})
            

#2)템플릿 제작
#2-1) 폼 태그 기반으로 사용자에게 입력양식 제공
#3)urls 등록
#3-1) path 함수를 기반으로 url 등록

Django8/src/vote/templates/vote/detail.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>투표 - {{ question.question_text }}</title>
</head>
<body>
	<h1>{{question.question_text}}</h1>
	<form action="{% url 'vote' %}"method="post">
	<!-- csrf 공격을 방지하기 위해 django에서 제공하는 기능 
		 form에 csrf_token이 없으면 웹서버 접근 거부
		 사용하지 않으려면 setting.py에서 설정-->
		{% csrf_token %}
		<!--해당 question 객체와 연결된 choice객체 추출 및 radio버튼 생성-->
		<!-- 템플릿에서는 함수 호출시 매개변수 사용 X
		  	 -> 따라서 매개변수를 사용하지 않는 함수만 사용 가능  -->
		  <!-- 외래키로 설정괸 모델클래스에서 나를 참조하는 객체를 추출시 
		  		객체.모델클래스명_set 으로 선택가능-->
		  <!-- c변수 : question객체와 연결된 Choice 객체 -->
		  <!-- for문 안에서 forllop.counter 사용 가능 : 현재 반복횟수를 의미 -->
		{% for c in question.choice_set.all %}
		
			<input type="radio" name="choice" 
					id = "choice{{ forloop.counter }}"value="{{c.id}}" />
					
			<label for="choice{{ forloop.counter }}">
				{{ c.choice_text }}
			</label>
			<a href="{% url 'deleteC' c.id %}">선택지 삭제</a>
			<a href="{% url 'updateC' c.id %}">선택지 수정</a>
		{% endfor %}
		<input type="submit"value="투표">
	</form>

	<a href="{%url 'updateQ' question.id %}"> 질문 수정</a>
<!--  <a href="http://127.0.0.1:8000/">메인페이지 가기</a>-->
	<a href="{%url 'index' %}">메인페이지 가기</a>
</body>
</html>

Django8/src/vote/templates/vote/index.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<ul>
	<!--  파이썬의 for, if문을 사용할때는 { % 를 사용
	view에서 넘겨받은 question_list는 리스트타입이므로 for에 사용 가능
	question_list의 요소에 저장된 Question 객체를 question변수에 넣음  
	for 의 끝을 알리기 위해서 endfor
	if의 끝을 알리기 위해서 endif를 추가로 작성해야함-->
		{% for question in question_list %}
			<li>
			<!--  <a href="http://127.0.0.1:8000/{ {question.id} }/">-->
			<a href="{% url 'detail' question.id%}">
			{{ question.question_text }} </a>
			<a href="{% url 'deleteQ' question.id %}">삭제</a>
			</li> 
		{% endfor %}
	</ul>




	<a href="{% url 'registerQ' %}">질문 등록</a>
	<a href="{% url 'registerC' %}">선택지 등록</a>
	<!---
	<H1>Hello django</H1>
	<p>파이썬 기반의 웹프로그래밍 { { hello } } </p>
	 --->
</body>
</html>

Django8/src/vote/templates/vote/registerC.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>선택지 작성</title>
</head>
<body>
	{% if error %}
	<p style="color: red">{{ error }}</p>
	{% endif %}
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="선택지 생성"/>
	</form>

</body>
</html>

Django8/src/vote/templates/vote/registerQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
</head>
<body>
	<form action="" method="post">
		{% csrf_token %}
		<!-- 폼객체.as_p : <input>, <label>를 <p>를 이용해서 HTML코드로 변환-->
		<!-- 폼객체.as_table : <input>,<label>를 테이블형태로 HTML코드 변환-->
		{{ form.as_p }}<!-- <input>, <label> 생성 -->
		<input type="submit"value="질문 등록">
		
	</form>

</body>
</html>

Django8/src/vote/templates/vote/result.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>설문조사 결과</title>
</head>
<body>
	<h1>{{obj.question_text}}</h1>
	<h3>{{obj.pub_data}}</h3>
	<table>
		<tr>
			<th>답변항목</th>
			<th>투표수</th>
		<tr>
		{% for c in obj.choice_set.all %}
			<tr>
				<td> {{c.choice_text}} </td>
				<td> {{c.votes}} </td>
			</tr>
	 	{% endfor %}
	</table>
	<a href="{% url 'vote' %}">메인페이지로 돌아가기</a>
	
</body>
</html>

Django8/src/vote/templates/vote/updateC.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>질문 수정</title>
</head>
<body>
<!-- 파이썬에서 if문에 변수이름만 넣은경우 해당 변수에 None값이 
아니면 True, None값이면 False -->
		{% if error%}
			<p> 에러 :{{error}} </p>
		{% endif %}
		
		<form action=""method="Post">
			{% csrf_token %}
			<table>
				{{ data.as_table }}
			</table>
			<input type="submit" value="선택지수정">
		</form>	
</body>
</html>




Django8/src/vote/templates/vote/updateQ.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>질문 수정</title>
</head>
<body>
	<form action=""method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="질문 수정">
	</form>
</body>
</html>