Django8/src/Django8/urls.py
from django.contrib import admin
from django.urls import path, include

from vote.views import *  #vote/view.py 에 있는 모든 함수/클래스 추가 
from vote.views import deleteC

urlpatterns = [
   
    path('admin/', admin.site.urls), #127.0.0.1:8000/admin/
    path('', index, name = 'index' ),#127.0.0.1:8000/
    #URL 등록 시 파이썬 코드에서 URL을 외워서 사용하지 않고,
    #별칭을 이용해서 사용할 수 있도록 name 매개변수에 문자열을 대입
    path('detail/<int:question_id>/',detail,name = 'detail' ),
    #path('admin/',index),
    #URL 추가 http://127.0.0.1:8000주소로 접근시 vore 어플리케이션의
    #view인 index 함수를 호출 하도록 등록
    path('result/<int:question_id>/',result,name='result'),
    path('vote/',vote,name='vote'),
    path('registerQuestion/', registerQ, name='registerQ') ,
    path('registerChoice/', registerC, name='registerC'),
    path('delete/<int:question_id>/',deleteQ,name='deleteQ'),
    path('deleteC/<int:choice_id>/',deleteC,name='deleteC'),
    path('updateQ/<int:question_id>/',updateQ,name="updateQ"),
    path('updateC/<int:choice_id>/',updateC,name="updateC"),
    #127.0.0.1/login/ URL 주소로 요청이 되면 view함수 호출 처리는 
    #customlogin 폴더에 있는 urls.py에서 처리하겠다 라고 등록
    path('login/',include('customlogin.urls')),
    path('auth/',include('social_django.urls',namespace ='social' ) ),
    path('blog/',include('blog.urls') )
]
#파일 관리 모듈 : numpy
from django.conf import settings
from django.conf.urls.static import static
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  




Django8/src/blog/urls.py

from django.urls import path
from .views import *
from blog.view import searchP

app_name = 'blog'

urlpatterns=[
    path('',index.as_view(),name='index'),
    path('<int:post_id>/',detail, name='detail'),
    path('search/',searchP,name='searchP')
    ]

Django8/src/customlogin/urls.py
from django.urls.conf import path
from .views import *
from django.contrib.auth import views
#app_name :해당 파일에서 별칭으로 등록된 url들을 호출할 때
#app_name: 별칭 으로 홀출해 충돌이 생기지 않도록 설정
app_name= 'customlogin'
#reverse('customlogin:signup')
#{% url 'customlogin:signup' %}
urlpatterns=[
    #127.0.0.1;8000/login/signup
    path('signup/',signup,name='signup'),
    #127.0.0.1:8000/login/signin
    #customlogin:signin
    path('signin/',signin,name='signin'),
    path('logout/',auth_logout, name='logout')
    ]

Django8/src/blog/models.py
from django.db import models

# Create your models here.
#글 종류
class PostType(models.Model):
    name = models.CharField('구분',max_length=50)
    def __str__(self):
        return self.name 
from django.conf import settings
#글
class Post(models.Model):
    type = models.ForeignKey(PostType,on_delete=models.CASCADE)
    headline = models.CharField('제목',max_length=200)
    content = models.TextField('내용',null=True,blank=True)
    #auto_now_add = True :객체가 생성되는 시점의 날짜/시간 정보를 기본값으로 사용
    pub_date = models.DateField('작성일',auto_now_add=True)
    #User 모델클래스를 사용할 때 
    #settings.AUTH_USER_MODEL 또는 User 모델클래스로 사용가능
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
#이미지
class Image(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    image = models.ImageField('이미지파일',upload_to='images/%Y/%m/%d')
    def delete(self, using=None, keep_parents=False):
        self.image.delete
        #image 변숟에 저장된 경로의 파일을 지우는 작업
        #why? Image 객체가 지워질때 image경로의 파일이 지워지지않으므로
        #객체가 삭제되는 delete함수 내에 이미지파일이 삭제되는 코드를 삽입
        return models.Model.delete(self, using=using, keep_parents=keep_parents)
#파일
class File(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    file = models.FileField('파일',upload_to='files/%Y/%m/%d')
    def delete(self, using=None, keep_parents=False):
        self.file.delete()
        return models.Model.delete(self, using=using, keep_parents=keep_parents)

Django8/src/blog/forms.py

from django.forms.models import ModelForm
from .models import *

class PostForm(ModelForm):
    class Meta:
        models = Post 
        fields = ['type','headline','content']
        #exclude = ['pub_date','author']
        
    def __init__(self,*args,**kwargs):
        super().__init__(self,*args,**kwargs)
        #사용자가 글 종류를 선택하지 않았을때의 기본값
        self.fields['type'].empty_label = None
        self.fields['type'].label = "글종류"

Django8/src/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.list import ListView


#제네릭뷰 : 장고에서 제공하는 여러가지 기능을 하는 뷰클래스
#class 뷰이름(제네릭뷰):
#ListView : 특정 객체의 목록을 다루는 기능을 가진 제네릭뷰
from django.views.generic.list import ListView 
import blog
from pip._vendor.requests.api import post
#render(request,'blog/index.html',{obj':obj})
class index(ListView):
    #template_name : html파일의 경로를 문자열로 저장 변수
    template_name = 'blog/index.html'
    #model : 어떤 모델클래스이 객체를 리스트업할 건지 명시하는 변수
    model= Post
    #context_object_name : 템플릿에서 사용할 객체 리스트를 저장한 변수 명 
    context_object_name = 'list'
    #paginate_by : 한 페이지에 몇개의 객체가 보여질지 설정하는 변수
    paginate_by = 5

def detail(request,post_id):
    obj = get_object_or_404(Post,pk=post_id)
    return render(request, "blog/detail.html", {'post':obj})



Django8/src/blog/templates/blog/base.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>dJango Blog</title>


</head>
<body>
	<a href="{% url 'index'%}">투표 어플리케이션</a>
	<a href="{% url 'blog:index' %}">블로그 어플리케이션</a>
	{%if user.is_authenticated %}
		<p>{{user.username}}님 환영합니다!
		<a href="{% url 'customlogin:logout' %}">로그아웃</a>
			
		</p>
	
	{%else%}
		<a href="{% url 'customlogin:signup' %}">회원가입</a>
		<a href="{%url 'customlogin:signip' %}">로그인</a>
	{%endif %}
<hr>
{% block content %}
{% endblock %}
<hr>
<p> 서울특별시 노원구 </p>
<p>tel : 010-1234-5678</p>
</body>
</html>

Django8/src/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block content %}
<table>
	<tr>
		<th> 제목/작성일 </th>
		<th>{{ post.headline }}/{{ post.pub_date }} </th>
	</tr>
	<tr>
		<th>내용</th>
		<td>
		{%for f in post.file_set.all %}
			<a href="{{ f.file.url }}" download>다운로드</a>
		{%endfor  %}
		{%for  i in post.image_set.all%}
			<img src="{{ i.image.url }}" width=20% />
			</img>
		{%endfor  %}
		{{post.content}}
		</td>
	</tr>
</table>
{% endblock %}

Django8/src/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
	{% if page_obj.has_previous %}
		<a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>
	{% endif %}
	{% if  page_obj.has_next %}
		<a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
	{% endif %}
	<br>
	<table style="width:100%">
		<tr>
			<th>글번호</th>
			<th>제목</th>
			<th>작성자</th>
			<th>작성일</th>
		</tr>
		{% for post in list %}
			<tr>
				<th>{{post.id}}</th>
				<th><a href="{% url 'blog:detail' post.id %}">{{post.headline}}</a></th>
				<th>{{post.author.username}}</th>
				<th>{{post.pub_date}}</th>			
			</tr>
		
		{% endfor %}
	</table>
	<form action="{% url 'blog:searchP' %}" method="GET">
	{% csrf_token %}
	<select name='type'>
		<option value='0'>제목</option>
		<option value='1'>내용</option>
	</select>
	<input type="text" name='query'/>
	<input type="submit" value="겸색"/>
</form>
{% endblock %}

Django8/src/blog/templates/blog/searchP.html
{% extends "blog/base.html" %}
{% block content %}

{% if list %}
		<table style="width:100%">
		<tr>
			<th>글번호</th>
			<th>제목</th>
			<th>작성자</th>
			<th>작성일</th>
		</tr>
		{% for post in list %}
			<tr>
				<th>{{post.id}}</th>
				<th><a href="{% url 'blog:detail' post.id %}">{{post.headline}}</a></th>
				<th>{{post.author.username}}</th>
				<th>{{post.pub_date}}</th>			
			</tr>
		
		{% endfor %}
	</table>
{% else %}
<p>검색결과가 없습니다.</p>
{% endif %}
<!-- 127.0.0.1:8000/blog/searchP -->
<form action="" method="GET">
	{% csrf_token %}
	<select name='type'>
		<option value='0'>제목</option>
		<option value='1'>내용</option>
	</select>
	<input type="text" name='query'/>
	<input type="submit" value="겸색"/>
</form>

{% endblock %}